# Same as cloudbuild-prod.yaml except with version tagging.
steps:
- name: 'gcr.io/cloud-builders/docker'
  secretEnv: ['GH_CLIENT_SECRET']
  entrypoint: 'bash'
  args:
  - "-c"
  - docker build --network cloudbuild --no-cache --build-arg GH_CLIENT_SECRET="$$GH_CLIENT_SECRET" -t gcr.io/$PROJECT_ID/editor-dev:latest -t gcr.io/$PROJECT_ID/editor-dev:$_TAG .

images:
- gcr.io/$PROJECT_ID/editor-dev

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github_app_client_secret/versions/latest
    env: 'GH_CLIENT_SECRET'
