name: Release please

on:
  push:
    branches:
    - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: GoogleCloudPlatform/release-please-action@v2
      id: release
      name: Release please
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-type: node
    - uses: actions/checkout@v2
      if: ${{ steps.release.outputs.release_created }}
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: 'https://registry.npmjs.org'
      if: ${{ steps.release.outputs.release_created }}
    - run: yarn install --frozen-lockfile
      if: ${{ steps.release.outputs.release_created }}
    - name: Publish npm package
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      if: ${{ steps.release.outputs.release_created }}
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
      if: ${{ steps.release.outputs.release_created }}
    - name: Deploy to prod
      run: make build-and-deploy-prod-tag tag=${{ steps.release.outputs.tag_name }}
      if: ${{ steps.release.outputs.release_created }}
